### ISSUE TITLE
set of tasks to improve code

### ISSUE THREAD

**Issue by amchagas** [Sussex-Neuroscience/many_pinetime_heartbeats#1]
The initial code for this project was cobbled together in small bursts and under a hard deadline, therefore it is not as good as it could be. In order to improve things and make this more manageable, we are creating this list of issues/wants/nice to haves we would like to see implemented:

the code right now is just a collection of scripts, where we are running an infinite loop and pinging three watches at a time. Which watches are being pinged is hard coded.

- [ ] #3
- [x] #2
```
Traceback (most recent call last):
  File "/Users/williamlindley/Documents/Alzheimers fund/thonny/alzheimer_installation/many_pinetime_heartbeats-main/multiple_devices1-4d.py", line 210, in <module>
    asyncio.run(find_all_devices_services())
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/williamlindley/Documents/Alzheimers fund/thonny/alzheimer_installation/many_pinetime_heartbeats-main/multiple_devices1-4d.py", line 95, in find_all_devices_services
    async with BleakClient(d) as client:
  File "/Users/williamlindley/Library/Python/3.10/lib/python/site-packages/bleak/__init__.py", line 491, in __aenter__
    await self.connect()
  File "/Users/williamlindley/Library/Python/3.10/lib/python/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
  File "/Users/williamlindley/Library/Python/3.10/lib/python/site-packages/bleak/backends/corebluetooth/client.py", line 128, in connect
    await self.get_services()
  File "/Users/williamlindley/Library/Python/3.10/lib/python/site-packages/bleak/backends/corebluetooth/client.py", line 208, in get_services
    cb_services = await self._delegate.discover_services(self._requested_services)
  File "/Users/williamlindley/Library/Python/3.10/lib/python/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 107, in discover_services
    return await future
bleak.exc.BleakError: disconnected


```

- [ ]  if there is time and easy, create a little user interface to display which kind of the data is being collected by the watches and what is being sent via OSC libraries

**Comment by KeaganKozlowski** [comment]
#2 
## Second issue i have two methods I have combined together to fix this issue:
#### 1. During the process of scanning for devices if no devices are found the user is show multiple messages depending on the problem
* If the user's bluetooth is not turned on the GUI displays "Please turn on your bluetooth", however you do not need to exit the app to get the app working again. All you have to do is press the back button and repress scan for devices
* If there is an unexpected error which I didn't encounter during the development process then the error message is provided to the user. Which is helpful for future issue finding.
#### 2. Taking data from the watches to be used with the OSC libraries
* The device in connected to once and information is extracted and transferred to a numpy array to be used later. And then the device is disconnected from 
* And in that cycle of connecting to devices it can no longer be connected to.
